name: 'chronograf/cypress/report'
on:
  workflow_run:
    workflows: ['chronograf/cypress']
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          artifact: results
          name: Cypress Tests
          path: ui/cypress/results/results-*.xml
          reporter: java-junit
          fail-on-error: false